server:
  port: 9999

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/database
    #      host: 127.0.0.1
    #      port: 27017
    #      database: database
  redis:
    host: 127.0.0.1
    port: 6379

