server:
  port: 9999

spring:
  profiles:
    active: jsp
  data:
    mongodb:
      uri: mongodb://localhost:27017/database
    #      host: 127.0.0.1
    #      port: 27017
    #      database: database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root


  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
#    root: debug
    com:
      adun:
        controller: debug


